# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b4a7eb1b83031cb0af5bdb844911a3b7ab37e0dee44895cf5c1203f7ef6e31db9188b57e00dd7e044beb47ece1215ed8108f466ca5c0a363104eeabe37797ab1

test:
  secret_key_base: 7ab0c80d437af4e97df549e2b5e4d0dc71d715ed4cb2655f4fa4186649544948b7692fcac05bc68c91db88270fcf9f3b4884ccc8f3b27d356e50020fac1b57d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
